// Vscode extensions:
code --install-extension ahmadawais.shades-of-purple
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension mquandalle.graphql
code --install-extension naumovs.color-highlight
code --install-extension PKief.material-icon-theme
code --install-extension wix.vscode-import-cost